# Generated by Django 5.2.3 on 2025-06-21 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("page_views", models.IntegerField(default=0)),
                ("form_submissions", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Analytics",
                "verbose_name_plural": "Analytics",
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual Seller"),
                            ("business", "Business/Company"),
                            ("retailer", "Retailer"),
                            ("wholesaler", "Wholesaler"),
                            ("manufacturer", "Manufacturer"),
                            ("distributor", "Distributor"),
                        ],
                        max_length=50,
                    ),
                ),
                ("business_description", models.TextField()),
                ("owner_name", models.CharField(max_length=200)),
                ("email_address", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=200)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "inventory_size",
                    models.CharField(
                        choices=[
                            ("small", "Small (1-50 items)"),
                            ("medium", "Medium (51-200 items)"),
                            ("large", "Large (201-500 items)"),
                            ("enterprise", "Enterprise (500+ items)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_admins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_sellers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller",
                "verbose_name_plural": "Sellers",
                "ordering": ["-created_at"],
            },
        ),
    ]
