# Generated by Django 5.0.2 on 2025-07-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='experience_level',
        ),
        migrations.AlterField(
            model_name='seller',
            name='inventory_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20),
        ),
    ]
