# Generated by Django 5.0.2 on 2025-07-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_remove_seller_business_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='business_type',
            field=models.CharField(choices=[('individual', 'Individual Seller'), ('business', 'Business/Company'), ('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('manufacturer', 'Manufacturer'), ('distributor', 'Distributor')], default='individual', max_length=50),
        ),
        migrations.AddField(
            model_name='seller',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='inventory_size',
            field=models.CharField(choices=[('small', 'Small (1-50 items)'), ('medium', 'Medium (51-200 items)'), ('large', 'Large (201-500 items)'), ('enterprise', 'Enterprise (500+ items)')], max_length=20),
        ),
    ]
