# Generated by Django 5.0.2 on 2025-08-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_pricingplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingplan',
            name='cancelled_monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price to show as crossed out (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='cancelled_yearly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original yearly price to show as crossed out (optional)', max_digits=10, null=True),
        ),
    ]
